version: '3'
services: 

  audit:
    build: ./audit/
    
  buyticket:
    build: ./buyticket/
  
  createlottery:
    build: ./createlottery/
    ports:
     - 5017:80
  
  findlottery:
    build: ./findlottery/
  
  maintenance:
    build: ./maintenance/
  
  pubKey:
    build: ./pubKey/
    ports:
     - 5020:80
  
  pvtkey:
    build: ./pvtkey/
     - 5021:80
  
  readbc:
    build: ./readbc/
  
  userinterface:
    build: ./userinterface/
  
  winningticket:
    build: ./winningticket/
    ports:
     - 5024:80
  
  writebc:
    build: ./writebc/
  
